---
title: "UFC EDA"
author: "Alvin Wendt"
date: "5/27/2021"
output: html_document
---

Read in Libraries
```{r}
library(tidyverse)
library(readxl)
library(hrbrthemes)
library(dlookr)
library(DataExplorer)
library(ggthemes)
library(corrplot)
library(reshape2)
library(randomForest)
```

Import Data
```{r}
data_raw <- read.csv("UFC Data.csv",header = TRUE)
```

```{r}
data_NoNAs<-data_raw[is.na(data_raw)] = 0
```

```{r}
EDA_Report <- create_report(data_raw)
```

```{r}
str(data_raw)
```


```{r}
describe(data_raw)
```


```{r}
correlate(data_raw)
eda_report(data_raw)
```


```{r}
plot_correlate(data_raw)
```


Spread Vs Anomalies
```{r}
data_raw %>%
  ggplot( aes(x=Spread, fill=as.factor(Anomaly))) +
    geom_histogram( color="#e9ecef", alpha=0.3, position = 'identity',bins = 100) +
    scale_fill_manual(values=c("#69b3a2", "#404080")) +
    labs(fill="")
```
```{r}
data_raw %>% ggplot(aes(x=Spread,  fill=as.factor(Anomaly))) + 
    geom_histogram(data=subset(data_raw,Anomaly == "0"),fill = "red", alpha = 0.4,bins = 70) +
    geom_histogram(data=subset(data_raw,Anomaly == "1"),fill = "blue", alpha = 0.2,bins = 70) +
      coord_cartesian(xlim = c(325, 3000))
```

```{r}
data_raw %>% ggplot(aes(x=Spread,y=stat(count)/sum(stat(count)),  fill=as.factor(Anomaly))) + 
    geom_histogram(data=subset(data_raw,Anomaly == "0"),fill = "red", alpha = 0.4,bins = 70) +
    geom_histogram(data=subset(data_raw,Anomaly == "1"),fill = "blue", alpha = 0.2,bins = 70) +
      coord_cartesian(xlim = c(325, 3000))
 
```

```{r}
data_raw %>%
  group_by(Spread,Anomaly) %>% 
  summarise(n = n()) %>% 
  mutate(freq = n / sum(n)) %>% 
  ggplot(aes(x=Spread, y=freq, fill=as.factor(Anomaly))) +
    geom_area(position = 'fill') +
    #scale_fill_manual(values=c("Red", "Blue")) +
      coord_cartesian(xlim = c(325, 3000)) + 
  labs(title = "Proportion of Odds per Spread",y="Proportion",fill = NULL)+
  scale_color_manual(labels = c("Favorite", "Underdog"), values = c("blue", "red"))+ scale_fill_brewer(palette = "Set1") 
```

```{r}

Data_RF<-randomForest(factor(Anomaly)~.,data_NoNAs,ntree=150)
Data_RF

```


```{r}
importance    <- importance(Data_RF)

varImportance <- data.frame(Variables = row.names(importance), 
                            Importance = round(importance[ ,'MeanDecreaseGini'],2))

# Create a rank variable based on importance
rankImportance <- varImportance %>%
  mutate(Rank = paste0('#',dense_rank(desc(Importance))))

# Use ggplot2 to visualize the relative importance of variables
ggplot(rankImportance, aes(x = reorder(Variables, Importance), 
                           y = Importance, fill = Importance)) +
  geom_bar(stat='identity') + 
  geom_text(aes(x = Variables, y = 0.5, label = Rank),
            hjust=0, vjust=0.55, size = 4, colour = 'red') +
  labs(x = 'Variables') +
  coord_flip() + 
  theme_classic()
```

